### ISSUE TITLE
[JOSS review] Add tags and release on Github

### ISSUE THREAD

**Issue by KedoKudo** [FrederikLizakJohansen/DebyeCalculator#13]
This is part of the review feedback for JOSS submission (https://github.com/openjournals/joss-reviews/issues/6024)

Currently there is no version tag or software releases available on Github, but the installed package does not have version.
It would be great if the developers can:

- use existing toolkits like `versioninggit` to automatically track versions
- add version to the published package
- tag a release on GitHub

**Comment by AndySAnker** [comment]
Thank you for making us aware that version tag and release was not included as part of the package. 

We have now added a version tag to the readme file and the published package (https://pypi.org/project/debyecalculator/)
<img width="935" alt="Screenshot 2024-01-17 at 11 52 45" src="https://github.com/FrederikLizakJohansen/DebyeCalculator/assets/41198747/98612213-3050-4fd3-88e9-6fdb85f05650">

We are also currently working on publishing a release on GitHub. More about that in the following days.

**Comment by FrederikLizakJohansen** [comment]
We have now tagged an official release on Github for our version 1.0.7: [Release Notes](https://github.com/FrederikLizakJohansen/DebyeCalculator/releases/tag/v1.0.7).

I will close this issue for now.
