### ISSUE TITLE
[JOSS review] Add documentation and publish it

### ISSUE THREAD

**Issue by KedoKudo** [FrederikLizakJohansen/DebyeCalculator#14]
This is part of the review feedback for JOSS submission (https://github.com/openjournals/joss-reviews/issues/6024)

Currently the software does not have a documentation. The usage and instructions are in the readme file and there is no API reference doc.

It would be great if the developers can:
- add a documentation folder like `docs`
- use sphinx or other software to help generate the API doc
- publish the doc on readthedoc or on GitHub page.

Also, it would be great to provide a step-by-step guild on how to use the software in the documentation, along with necessary screenshots.

**Comment by AndySAnker** [comment]
Thank you for the great suggestion of using sphinx to generate an API and publish it in readthedoc.

We have done this (https://debyecalculator.readthedocs.io/en/latest/) while maintaining step-by-step use of 'DebyeCalculator' in the readme file of the project. 

We have also added badges to the readme file of the pypi, python version, license, ChemRxiv file and readthedocs.
<img width="1037" alt="Screenshot 2024-01-17 at 11 36 43" src="https://github.com/FrederikLizakJohansen/DebyeCalculator/assets/41198747/3853525a-5abb-4d87-aca5-d7029369cd79">

I will close this issue - let us know if it should be reopened.
