### ISSUE TITLE
[JOSS review] Named_tuple

### ISSUE THREAD

**Issue by AndySAnker** [FrederikLizakJohansen/DebyeCalculator#20]
This is part of the review feedback for JOSS submission (https://github.com/openjournals/joss-reviews/issues/6024)

@marcocamma suggests using a named_tuple or dictionary as return values instead of simple tuples.

**Comment by FrederikLizakJohansen** [comment]
Thank you for the suggestion!
This issue has been adressed and resolved in #21. Therefore I am closing this issue. Feel free to reopen or create a new issue, if the current implementation can be further improved.
