### ISSUE TITLE
[JOSS review] Instructions missing for how the software wants to access the GPU

### ISSUE THREAD

**Issue by elena-pascal** [FrederikLizakJohansen/DebyeCalculator#24]
This is part of the review feedback for JOSS submission (https://github.com/openjournals/joss-reviews/issues/6024)

I followed the install instructions which ran cleanly. I have an NVIDIA RTX card on this PC. I expected then that I can run 
```
calc = DebyeCalculator(device='cuda')
```
actually, I expected to be able to run `device='gpu'` since the class documentation only talks about cpu/gpu.  

> (e.g., 'cuda' for GPU or 'cpu' for CPU). Default is 'cuda' if the computer has a GPU.

But I actually don't have `cuda` and I get ```AssertionError("Torch not compiled with CUDA enabled")```

It would be nice to have either  more detailed requirements, specifically on GPU drivers and software needed or more details instructions on how to achieve the GPU interface layers DebyeCalculator expects.

I think either send the user to install `torch` following the [website instructions,](https://pytorch.org/get-started/locally/) or offer the instructions for the platform you want to support. `pip install torch` is not guaranteed to give you something that can talk to the GPU on any platform configuration under the sun.

**Comment by FrederikLizakJohansen** [comment]
Thank you for bringing this to our attention. This is something that we've naturally been concerned about as well. We've made updates to the installation instructions and provided more information about the prerequisites for using GPU support in the DebyeCalculator package, as well as implemented more explicit warnings about CUDA availability into the software. With these changes, PyTorch will not be installed with the DebyeCalculator package within the pip-installation, but instead be a prerequisite to the package. To sum up:

1. **PyTorch Dependency:** We want to clarify that DebyeCalculator depends on PyTorch, and users need to install PyTorch separately before using our package. We've updated the README to include PyTorch as a prerequisite. Users are now directed to install PyTorch from the official website before proceeding with DebyeCalculator installation.

2. **More Specific Error Handling:** In response to your feedback, we've enhanced the error/warning messages. If PyTorch is not installed, users will now receive a more informative message, guiding them to install PyTorch with a direct link to the official PyTorch installation guide as well as this Github page. The README now also contains a dedicated "GPU Support" section that provides steps for verifying CUDA availability.

These changes will be applied to **DebyeCalculator v.1.0.4 and onwards through the PyPI installation (https://pypi.org/project/debyecalculator/)**

We hope these enhancements address your concerns. If you encounter any further issues or have additional suggestions, don't hesitate to let us know, so we can reopen the issue.
