### ISSUE TITLE
[JOSS review] Instructions missing on running tests

### ISSUE THREAD

**Issue by elena-pascal** [FrederikLizakJohansen/DebyeCalculator#25]
This is part of the review feedback for JOSS submission (https://github.com/openjournals/joss-reviews/issues/6024)

This is an easy one, but adding the line needed to run the tests in the instructions would be nice.

**Comment by FrederikLizakJohansen** [comment]
Thank you for the suggestion! 
The change was added in 8beadc6

I am closing this issue here. Feel free to reopen the issue if you would like to see any further changes made to this.
